database:
  url: postgresql://kokoro:kokoro@localhost:5432/kokoro

task_center:
  url: http://localhost:8000

api:
  key: kokoro_ITP92OEE-gehm1BKRglHAmRkpfHLtW7Wj_WhVK4g4xc

logging:
  level: INFO
  file: logs/website_admin.log

